name: Deploy

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      -name: Install dependencies
        run: npm install
      with: 
        build: npm run build
        start: npm run preview
